name: run updator

on:
    schedule:
        - cron: '*/5 * * * *' # Runs every 5 minutes

    workflow_dispatch:

jobs:
    build:
        permissions:
            contents: write
            pages: write

        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4 # checkout the repository content to github runner

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12' # install the python version needed

            - name: install python packages
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: execute py script # run main.py
              run: python update.py
              env:
                  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
                  CF_EMAIL: ${{ secrets.CF_EMAIL }}
                  TEST_ENV: ${{ secrets.TEST_ENV }}
